channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.9
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu129
      - torch==2.8.0+cu129
      - torchvision==0.23.0+cu129
      - pytorch-lightning==2.5.4
      - hydra-core==1.3.2
      - timm==1.0.19
      - segmentation-models-pytorch==0.5.0
      - torchmetrics==1.8.1
      - opencv-python-headless==4.12.0.88
      - ftputil