channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - mil --no-index --find-links=%MIL_PATH%\..\scripting\pythonwrapper\dist
      - matplotlib
      - numpy
      - opencv-python-headless
      - pillow
      - scipy
      - tqdm
